version: '3.8'

services:
  # SQL Server Database
  fcms-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fcms-sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - fcms-net

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fcms-net

  # The Web API application
  fcms-api:
    build:
      context: .
      dockerfile: src/Presentation/FCMS.WebApi/Dockerfile
    container_name: fcms-api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=fcms-sql;Database=FCMS_Db;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    depends_on:
      - fcms-sql
      - rabbitmq
    networks:
      - fcms-net

networks:
  fcms-net:
    driver: bridge