name: .NET Microservices CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # docker-compose -> docker compose
      - name: Start Infrastructure (SQL & RabbitMQ)
        run: docker compose up -d fcms-sql rabbitmq

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release

      - name: Run xUnit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      # docker-compose -> docker compose
      - name: Stop Infrastructure
        if: always()
        run: docker compose down