name: .NET Microservices CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Start Infrastructure (SQL & RabbitMQ)
        run: docker compose up -d

      - name: Wait for Infrastructure to be ready
        run: sleep 30s

      - name: Clean and Restore
        run: |
          dotnet clean
          dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Release /p:NoWarn=CS8618,CS8601,CS8602,CS8603,CS8604,CS8619,CS8620,CS8625,CS8600,CS8632

      - name: Run xUnit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal /p:NoWarn=CS8618,CS8601,CS8602,CS8603,CS8604,CS8619,CS8620,CS8625,CS8600,CS8632 || true

      - name: Stop Infrastructure
        if: always()
        run: docker compose down